# Generated by Django 3.2.7 on 2021-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('controler', models.CharField(max_length=15)),
                ('data', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=12)),
                ('access', models.CharField(max_length=100)),
                ('receptor', models.CharField(max_length=15)),
                ('resident', models.CharField(max_length=50)),
            ],
        ),
    ]
