# Generated by Django 3.2.7 on 2021-09-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('serial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.serial')),
            ],
        ),
    ]
